### ISSUE TITLE
Multi-tasking or synchronous optimisation

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#151]
Just an idea for some multi-tasking or synchronous optimisation.

Once DIC has done this phase
> Creating .scm (LBA) 179351/179351

Am I correct that DICUI could read the files it needs to on the disc?

That way you make use of the time that DIC is unscrambling, calc checksums, to do your thing. 

> No C2 errors
> Copying .scm to .img
> Descrambling data sector of img (LBA) 179351/179351
> Exec ""C:\Users\7\Desktop\Plextor\DICUI\Programs\EccEdc.exe" check "C:\Users\7\D
> esktop\Plextor\DICUI\ISO\TITAN AE\TITAN AE.img""
> FILE: C:\Users\7\Desktop\Plextor\DICUI\ISO\TITAN AE\TITAN AE.img
> Checking sectors (LBA) 179351/179351
> [NO ERROR] User data vs. ecc/edc match all
> Creating bin, cue and ccd (Track)  1/ 1
> Calculating hash: TITAN AE.scm [421835904/421835904]
> Calculating hash: TITAN AE.img [421835904/421835904]
> Calculating hash: TITAN AE.bin [94759728/421835904]

Then when DIC finishes, DICUI can finish/eject straight away.

Right now, DIC finishes with its beeps and DICUI says

> Information filling complete!

then there is 30 seconds or so as DICUI says 

> Extracting information complete!
> Formatting extracted information...
> Formatting complete!
> Writing information to !submissionInfo.txt...
> Writing complete!
> All submission information gathered!
> Dumping complete!
> Ejecting disc in drive E
> 

and finally "dump complete!"

**Comment by mnadareski** [comment]
Since there is no guarantee of the time when DIC will be complete, it would be ill-advised to try to grab information before it is done. The only parts of information gathering that take any substantial time are the external call to Redump (if possible) and the copy protection scan, both of which are optional. The call to Redump requires the hashes to exist and the copy protection scan requires an open handle to the disc drive (which is locked when DIC is doing its thing).

**Comment by gingerbeardman** [comment]
OK thanks, then I'll deactivate the copy protection scan.
