### ISSUE TITLE
Behaviour of tab is inconsistent on Disc Information dialog

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#162]
On some fields tab moves to next field (eg Data/LO) 
- this is expected behaviour

On others it inserts a tab character (eg Label/L1)
- this is unexpected behaviour 

![Screen shot 2019-09-20 at 14 11 51](https://user-images.githubusercontent.com/49612/65329561-9f02d200-dbb0-11e9-9e38-3b49be557fe6.png)

**Comment by sadikyo** [comment]
I believe this is setup intentionally, because the ringcode fields can have tabs in them.  I believe the idea is to get the data filled in to the txt/json as completely and accurately as possible.  Including the actual tabs in the fields, makes it such that they can be later copied / submitted / imported (eventually, potentially) in a way that requires less processing.  The trade-off for this is perhaps navigating the disc collection dialog, but it would just require clicking on the next field.

**Comment by gingerbeardman** [comment]
Understood.
