### ISSUE TITLE
!submissionInfo.* store default contents before dialog is closed

### ISSUE THREAD

**Issue by superg** [SabreTools/DICUI#181]
This is more of a suggestion. It would be nice if DICUI saved default empty !submissionInfo.txt right after the dump and before I close the dialog with text boxes. Asking user to enter all the fields is cool but a few times I lost generated !submissionInfo.txt and I can't explain why did it happen (I usually keep DICUI open all the time. Reboot? I didn't pay much attention when exactly does it happen). I dump a lot and that would help me to save time and not to redump the same disc again just for !submissionInfo.txt generation. Or maybe a checkbox in options to be able to disable user dialog and just store the file (old behaviour like it used to be).

**Comment by mnadareski** [comment]
There is an option like that in the UI already. Check the options dialog and try again.

**Comment by mnadareski** [comment]
I think the ask might be "output a file before it shows the dialog". If that's the case, I'm closing this as a wontfix, since there's no reasonable way of doing that without some very dumb stuff where it writes out, unlocks, lets you enter things in, and then... overwrite it. I'll wait for confirmation of the ask, before closing this, though.

**Comment by superg** [comment]
Oh no, the option not to show gui is fine, all I care about is that right after the dump the file is created automatically.

**Comment by mnadareski** [comment]
Closing as wontfix.
