### ISSUE TITLE
DICUI reports drive firmware isn't up to date but DIC dumps fine via CLI

### ISSUE THREAD

**Issue by touche112** [SabreTools/DICUI#199]
When trying to dump with my LG BU40N, DICUI reports that my firmware is out of date.  However, when using DIC directly via CLI, there are no errors and it dumps fine.  Attached is _drive.txt.
[boob_drive.txt](https://github.com/SabreTools/DICUI/files/4494171/boob_drive.txt)

**Comment by InternalLoss** [comment]
I can confirm this also seems to be happening with my ASUS drive I usually use for DVD disc dumping (aka my in-built drive) - https://cdn.discordapp.com/attachments/447910497963081730/702039078396362803/DVDVolume_drive.txt

**Comment by mnadareski** [comment]
Strictly speaking, this is an issue with DIC, but I'll remove the explicit pre-dump call to DIC for the firmware check until it's fixed.

**Comment by touche112** [comment]
> Strictly speaking, this is an issue with DIC, but I'll remove the explicit pre-dump call to DIC for the firmware check until it's fixed.

A firmware check toggle would be nice!

**Comment by mnadareski** [comment]
I think I'm being a bit misunderstood here. DIC checks for firmware version of the dumping drive. DICUI doesn't actually care what drive you're trying to use, but we had put code in that tries to use DIC to check the firmware *before* dumping so that it wasn't as jarring if the dump failed seemingly at random right at the start. The change that "fixes" this just removes that preemptive call to DIC, so unsupported firmware versions will fail as they did previously. If DIC broke something in reporting firmware issues when invoking the drive speed command, then fantastic, it just makes it less user-friendly in the end.

**Comment by touche112** [comment]
I completely understand what you're saying.  What I was suggesting was a toggle in DICUI for the preliminary call to DIC for a firmware check.  That would eliminate any of these issues in the future if DIC happens to bork their firmware check again.
