### ISSUE TITLE
DICUI doesn't save custom output directory

### ISSUE THREAD

**Issue by SilasLaspada** [SabreTools/DICUI#217]
When trying to change the output directory, DICUI asks if I would like to save these changes. Hitting yes reverts the output directory and other settings such as parameters back to default, prints "Starting dumping process..." to the console, but doesn't actually start the dump. When I only specify custom parameters, hitting yes saves the parameters.

**Comment by mnadareski** [comment]
As discussed on Discord, this is an out-of-order issue caused by user error.
Here is the order of events that happened to trigger the above:
- Toggle custom parameter checkbox in the UI
- Custom parameters changed, not including output path
- Custom parameter checkbox not toggled back
- Output path changed in normal UI option
- Dump started and accept the custom parameter change

This resulted in the scenario that the new output path from the UI option was overridden by the value in the custom parameters, which was the old value. Due to how the custom parameters can be essentially anything, if they're not saved by the time the dumping program is invoked, it will override anything in the dump environment, regardless of if it was changed from their original values or not. So the value wasn't going to "default", it was just going to the value in the custom parameters.

As a slight remedy to this, the popup that already asks users if they wanted the custom parameters to be applied will also mention that any values in the custom parameters will override settings and profiles selected in the UI. This will hopefully alleviate more of these sort of "bugs" from showing up as this is expected behavior.

**Comment by mnadareski** [comment]
This information has now been reflected into the Wiki here: https://github.com/SabreTools/DICUI/wiki/DICUI
