### ISSUE TITLE
DICUI hangs at "Running any additional tools... please wait!" on IBM PC DOS disc

### ISSUE THREAD

**Issue by xperia64** [SabreTools/DICUI#218]
I have attempted to dump a IBM PC DOS game on my cross-flashed WH16NS40, and while the DiscImageCreator step succeeds, the "Running any additional tools... please wait!" step hangs the entire DICUI application (which I see in the source code shouldn't do anything except for Sega Saturn discs). Buttons completely unresponsive etc. There is activity on the drive LED during this process. If I leave it running long enough, DICUI closes entirely. If I eject the disc, DICUI continues successfully and prompts me to fill out the information to submit.

**Comment by mnadareski** [comment]
This has come up quite a few times, and I've answered it all of those times. Copy protection scan, especially on older versions, would appear to freeze the application as it scanned. With discs that had a large enough number of files and/or a system with relatively little RAM, this would cause issues which could include DICUI crashing. More recent stable and WIP versions have alleviated that somewhat due to changes in design, including making it so the scanning should not freeze anything now.

With the above being said, copy protection scanning can just be turned off and something like PiD can be used after. It's not a required step. Please look at the options menu for more details.

**Comment by xperia64** [comment]
Ah yeah, the AppVeyor builds work fine, and the disc I was dumping did indeed have many small files.

Still not sure why the old version crashed as it shouldn't have been anywhere close to OOMing, but I'll take it.
